export enum DiplomeType {
  BAC = 'baccalauréat', 
  DUT = 'diplome universitaire de technologie',
  DEUG = 'diplome d\'études universitaires général',
  DEUST = 'diplome d\'études universitaires scientifiques et techniques', 
  BTS = 'Brevet de Technicien Supérieur',
  DTS = 'Diplôme de Technicien Spécialisé',
  CI = 'cycle ingénieur',
  LICENCE = 'licence',
  LICENCE_PROFESSIONNELLE = 'licence professionnelle',
  MASTER = 'master',
  MASTER_SPECIALISE = 'master specialise',
  MASTER_EN_SCIENCE_TECHNIQUE = 'master en science et technique',
  DOCTORATE_EN_MEDICINE = 'doctorate en medicine',
}
